apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gdp4xyqqb-python 
  janus-idp.io/tekton: gdp4xyqqb-python
  backstage.io/kubernetes-id: gdp4xyqqb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gdp4xyqqb-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  